version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "01:45"
  reviewers:
  - yuriytkach
  assignees:
  - yuriytkach
  labels:
  - "automerge_github"
  - "dependencies"
  commit-message:
    prefix: "build(deps)"
    prefix-development: "build(deps-dev)"
  ignore:
    - dependency-name: com.amazonaws:aws-java-sdk-dynamodb
      versions:
        - "> 1.12.333"
        - "< 1.13"
